export { VisitingLecturerCreatePage } from './VisitingLecturerCreatePage'
export { VisitingLecturerEditPage } from './VisitingLecturerEditPage'
export { VisitingLecturersActivePage } from './VisitingLecturersActivePage'
export { VisitingLecturersInactivePage } from './VisitingLecturersInactivePage'
export { VisitingLecturersPendingPage } from './VisitingLecturersPendingPage'
